; PlatformIO Project Configuration File
; XIAO nRF54LM20A V2 blink + USB CDC console (V2-only sample)
[env:seeed-xiao-nrf54lm20a-v2]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-nrf54lm20a-v2
monitor_speed = 115200
