; XIAO STM32C5 GPIO all-pins command test over USB CDC

[env:seeed-xiao-stm32c5]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 1000000
platform_packages = framework-zephyr@~3.40400.0
